name: flutter_portfolio
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # UI
  intl: ^0.19.0
  flutter_svg: ^2.0.10+1
  cupertino_icons: ^1.0.6
  cached_network_image: ^3.3.1
  lottie: ^3.1.2

  # Responsive UI
  responsive_framework: ^1.4.0

  # State Management
  flutter_bloc: ^8.1.6
  bloc: ^8.1.4

  # Navigator
  auto_route: ^8.3.0

  # Dependency Injection
  injectable: ^2.4.4
  get_it: ^7.7.0

  # Architecture
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  flutter_gen: ^5.6.0

  # Logger
  logger: ^2.4.0

  # Firebase
  firebase_core: ^3.3.0
  firebase_app_check: ^0.3.0+3
  firebase_analytics: ^11.2.0
  firebase_crashlytics: ^4.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  build_runner: ^2.4.11
  freezed: ^2.5.2
  injectable_generator: ^2.4.4  
  json_serializable: ^6.8.0
  auto_route_generator: ^8.1.0
  flutter_gen_runner: ^5.6.0
  path_provider: ^2.1.4

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
    - assets/lottie/

flutter_gen:
  output: lib/gen/ # Optional (default: lib/gen/)
  line_length: 80 # Optional (default: 80)
  arb_dir: lib/l10n/

  assets:
    outputs:
      directory_path_enabled: true
      class_name: Assets

  # Optional
  integrations:
    flutter_svg: true
    lottie: true